### ISSUE TITLE
Backbone(DOM Manipulation) and Overall Project Structure Guidance

### ISSUE THREAD

**Issue by ryu15** [efosao12/FinalProjectTravel#2]
Dear Mr. Fritz,

We need some assistance regarding Backbone(DOM manipulation) and overall guidance.

best,
Ryusuke

**Comment by efosao12** [comment]
We are currently testing a few options regarding the empty method and append. Will get back to you after we have the results or failure of it. 
Efosa

**Comment by andrewfritz86** [comment]
Sounds good, I closed the duplicate issue. Just comment here (with some code!)
